### ISSUE TITLE
docker-compose file

### ISSUE THREAD

**Issue by xerootg** [Dr4kn/audible-downloader#1]
Hi! thanks for this, I'm using this on my nas with audiobookshelf!

Some people are intimidated by things they have to build themselves, so I figured I would share how I got it up and running:

Clone this repo into the folder with my gigantic docker-compose file, add this to it:
```yaml
services:
  audiobook_downloader:
    container_name: audiobook_downloader
    build:
      context: ./audible-downloader
    volumes:
      - ${STORAGE_DIR}/audiobooks:/audiobooks
      - ${CONFIG_DIR}/audiobook_dl:/config
```

I've got a `.env` that has STORAGE_DIR and CONFIG_DIR defined.

then run `docker compose build`
and then `docker compose exec audiobook_downloader audible quickstart`
defaults on everything, except `Do you want to login with external browser? [y/N]: y`
manually sync everything once by running `docker compose exec audiobook_downloader python /app/audiobookDownloader.py`
and finally, `docker compose up -d`  to have it join my pool of other things.

so not so much an issue, but maybe some docs? :D
